version: 1
services:
  - type: web
    name: your-flask-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app # Змініть 'app:app' на ім'я вашого файлу та змініть назву додатку
